/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HotAreaCheck: typeof import('./src/components/hot-area-check.vue')['default']
    Versions: typeof import('./src/components/Versions.vue')['default']
  }
}
